airlines/urls.py
from django.contrib import admin
from django.urls import path, include

# My imports
from airlines.views import  AirlinesListingView, AirlinesDetailView, AirlinesCreateView, AirlineDeleteView, AirlinesUpdateView
#aiport imports
from airlines.views import AirportListView, AirportDetailView, AirportsCreateView, AirportDeleteView, AirportsUpdateView

app_name = "airlines"

urlpatterns = [
    #AIRLINES
    path("list/", AirlinesListingView.as_view(), name="list-view"),
    path("list/<str:start_str>/", AirlinesListingView.as_view(), name="filtered-list-view"),
    path("detail/<int:pk>/", AirlinesDetailView.as_view(), name="detail-view"),
    path("create/", AirlinesCreateView.as_view(), name="create-view"),
    path("delete/<int:pk>/", AirlineDeleteView.as_view(), name="delete-view"),
    path("update/<int:pk>/", AirlinesUpdateView.as_view(), name="update-view"),
    # AIRPORTS
    path("airport-list/", AirportListView.as_view(), name="airport-list-view"),
    path("airport-list/<str:start_str>", AirportListView.as_view(), name="filtered-airport-list-view"),
    path("airport-detail/<int:pk>/", AirportDetailView.as_view(), name="airport-detail-view"),
    path("airport-create/", AirportsCreateView.as_view(), name="airport-create-view"),
    path("airport-delete/<int:pk>/", AirportDeleteView.as_view(), name="airport-delete-view"),
    path("airport-update/<int:pk>/", AirportsUpdateView.as_view(), name="airport-update-view"),
]

project1/urls.py
from airlines.views import  airline_home_page
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
#from project1.views import AccountLoginView, AccountLogoutConfirmationView, AccountLogoutYesNoView, AccountLogoutView

urlpatterns = [
    path("", airline_home_page, name="home"),
    path("admin/", admin.site.urls),
    path("airlines/", include("airlines.urls")),
    # LOGIN LOGOUT
    #path('login-confirmation/', AccountLoginConfirmationView.as_view(), name='login-confirmation'),
    #path('logout-confirmation/', AccountLogoutConfirmationView.as_view(), name='logout-confirmation'),
    #path('logout-yes-no-confirmation/', AccountLogoutYesNoView.as_view(), name='logout-yes-no-confirmation'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout')
]

airlines/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse_lazy

class Alliance(models.Model):
    """Shows to which alliance does each airline belong to"""
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    def alliances_list_as_string(self):
        """Returns a string representation of alliance instances"""
        alliances = self.objects.all()
        return ", ".join(alliance.name for alliance in alliances)

# Basic airline model
class Airline(models.Model):
    airline_name = models.CharField(max_length=100, blank=True)
    airline_code = models.IntegerField( blank=True)
    founded = models.DateField(null=True, blank=True)
    headquarters_city_code = models.CharField(max_length=3, blank=True)

    # Many-to-many relationship with Alliance
    alliance = models.ManyToManyField(Alliance,related_name='airline_alliance', blank=True)

    def get_absolute_url(self):
        """Returns the url to access a detail page of this model"""
        return reverse_lazy('airlines:detail-view', kwargs={'pk': self.pk})

    def __str__(self):
        return self.airline_name


# Basic airport model
class Airport(models.Model):
    airport_name = models.CharField(max_length=100)
    country_code = models.CharField(max_length=2)
    city_code = models.CharField(max_length=3)
    airport_code = models.CharField(max_length=4, unique=True)

    def get_absolute_url(self):
        """Returns the url to access a detail page of this model"""
        return reverse_lazy('airlines:airport-detail-view', kwargs={'pk': self.pk})

    def __str__(self):
        return self.airport_name

airlines/forms.py
from django import forms
from .models import Airline, Airport
from django.core.exceptions import ValidationError

class AirlineModelForm(forms.ModelForm):
    class Meta:
        model = Airline
        fields = "__all__"
        labels = {
            "airline_name": "Airline name",
            "airline_code": "Airline code",
            "founded": "Founded",
            "headquarters_city_code": "Headquarters city code",
        }
        widgets = {
            'alliance': forms.SelectMultiple(attrs={'class': 'form-control'})
        }
        help_texts = {
            "airline_name": "Enter full airline name",
            "airline_code": "Enter three digit airline code",
            "founded": "Enter date when the airline was founded",
            "headquarters_city_code": "Enter three letter city code",
        }

    def clean_airline_name(self):
        """Checking for duplicate data"""
        airline_name = self.cleaned_data.get('airline_name')

        dupe_airline = Airline.objects.filter(airline_name=airline_name).exclude(pk=self.instance.pk).exists()
        if dupe_airline:
            raise ValidationError("Airline name already exists")

        return airline_name

class AirportModelForm(forms.ModelForm):
    class Meta:
        model = Airport
        fields = "__all__"
        labels = {
            "airport_name": "Airport name",
            "country_code": "Country code",
            "city_code": "City code",
            "airport_code": "Airport code",
        }
        help_texts = {
            "airport_name": "Enter full airport name",
            "country_code": "Enter two letter country code",
            "city_code": "Enter three letter city code",
            "airport_code": "Enter three letter airport code",

        }

    def clean_airport_name(self):
        """Checking for duplicate data"""

        airport_name = self.cleaned_data.get("airport_name")

        dupe_airline = Airport.objects.filter(airport_name=airport_name).exclude(pk=self.instance.pk).exists()
        if dupe_airline:
            raise ValidationError("Airport name already exists")

        return airport_name


class JustButtonForm(forms.Form):
    """
    Empty form for just button needs
    """

airlines/views.py
from airlines.models import Airline, Airport
from django.shortcuts import render
from django.db.models import Q

import airlines
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from airlines.forms import AirlineModelForm, AirportModelForm, JustButtonForm
from pyexpat.errors import messages
from django.contrib import messages


#------------------------------------------------------------------------
# AIRLINE VIEWS
#------------------------------------------------------------------------
def airline_home_page(request):
    """Airlines home page"""
    return render(request, 'home_page.html')

class AirlinesListingView(ListView):
    template_name = "airline_listing_template.html"
    model = Airline
    context_object_name = "airlines"

    def get_queryset(self):
        queryset = super().get_queryset()

        start_str = self.request.GET.get('start_str')
        if start_str:
            queryset = queryset.filter(
                Q(airline_name__icontains=start_str) |
                Q(airline_code__icontains=start_str)
            )

        return queryset

class AirlinesDetailView(DetailView):
    template_name = "airline_detail_template.html"
    model = Airline
    context_object_name = "airline"

class AirlinesCreateView(LoginRequiredMixin,CreateView):
    template_name = "airline_create_template.html"
    model = Airline
    form_class = AirlineModelForm
    login_url = reverse_lazy('login')

    def get_success_url(self):
        return self.object.get_absolute_url()

    def dispatch(self, request, *args, **kwargs):
        """Gives error message when not logged in"""
        if not request.user.is_authenticated:
            messages.error(request, message='You have to login to Create a new Airline.')
        return super().dispatch(request, *args, **kwargs)

class AirlineDeleteView(LoginRequiredMixin,DeleteView):
    template_name = "airline_delete_template.html"
    model = Airline
    context_object_name = "airline"
    success_url = reverse_lazy("airlines:list-view")
    form_class = JustButtonForm
    login_url = reverse_lazy('login')

    def dispatch(self, request, *args, **kwargs):
        """Gives error message when not logged in"""
        if not request.user.is_authenticated:
            messages.error(request, message='You have to login to Delete this Airline.')
        return super().dispatch(request, *args, **kwargs)

class AirlinesUpdateView(LoginRequiredMixin,UpdateView):
    template_name = "airline_update_template.html"
    model = Airline
    form_class = AirlineModelForm
    login_url = reverse_lazy('login')

    def dispatch(self, request, *args, **kwargs):
        """Gives error message when not logged in"""
        if not request.user.is_authenticated:
            messages.error(request, message='You have to login to Update Airlines.')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return self.object.get_absolute_url()
#------------------------------------------------------------------------
# AIRPORT VIEWS
#------------------------------------------------------------------------
class AirportListView(ListView):
    template_name = "airport_listing_template.html"
    model = Airport
    context_object_name = "airports"

    def get_queryset(self):
        """Fetches customer imput for filtering airline data"""
        queryset = super().get_queryset()

        start_str = self.request.GET.get('start_str')

        if start_str:
            queryset = queryset.filter(
                Q(airport_name__icontains=start_str) |
                Q(airport_code__icontains=start_str)
            )
        return queryset

class AirportDetailView(DetailView):
    template_name = "airport_detail_template.html"
    model = Airport
    context_object_name = "airport"

class AirportsCreateView(LoginRequiredMixin, CreateView):
    template_name = "airport_create_template.html"
    form_class = AirportModelForm
    login_url = reverse_lazy('login')

    def dispatch(self, request, *args, **kwargs):
        """Gives error message when not logged in"""
        if not request.user.is_authenticated:
            messages.error(request, message='You have to login to Create a new Airport.')
        return super().dispatch(request, *args, **kwargs)


    def get_success_url(self):
        return self.object.get_absolute_url()

class AirportDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "airport_delete_view.html"
    model = Airport
    context_object_name = "airport"
    success_url = reverse_lazy("airlines:airport-list-view")
    login_url = reverse_lazy('login')

    def dispatch(self, request, *args, **kwargs):
        """Gives error message when not logged in"""
        if not request.user.is_authenticated:
            messages.error(request, message='You have to login to Delete Airport.')
        return super().dispatch(request, *args, **kwargs)

class AirportsUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "airport_update_view.html"
    model = Airport
    form_class = AirportModelForm
    login_url = reverse_lazy('login')

    def dispatch(self, request, *args, **kwargs):
        """Gives error message when not logged in"""
        if not request.user.is_authenticated:
            messages.error(request, message='You have to login to Update Airport.')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return self.object.get_absolute_url()

airlines/templates/snippets/airline_info1.html
  <div class="container">
    <div class="row mt-3">
      <div class="col">
        <p class="fs-5">
          The world of aviation is vast and interconnected, with over 5,000 airlines and 40,000 airports spanning the globe.
          From major international carriers and bustling mega-hubs to regional airlines and small airstrips,
          the aviation industry plays a crucial role in connecting people, places, and cultures.
          Whether you're planning your next trip, tracking flights, or simply exploring the fascinating world of aviation,
          this page is your one-stop resource for everything airlines and airports.
        </p>
      </div>
    </div>
  </div>
 <div class="container">
    <div class="row mt-3">
      <div class="col">
        <h3>Did You Know?</h3>
        <p class="fs-5">
          The largest airline by fleet size is American Airlines, operating over 900 aircraft.<br>
          The busiest airport by passenger traffic is Hartsfield-Jackson Atlanta International Airport (ATL), handling more than 100 million travelers annually.<br>
          The longest non-stop commercial flight is operated by Singapore Airlines, flying from Singapore to New York, covering over 9,500 miles.<br>
          The highest-altitude commercial airport is Daocheng Yading Airport (DCY) in China, sitting at 14,472 feet above sea level.<br>
          The world's oldest operating airport is College Park Airport (CGS) in Maryland, USA, established in 1909.
        </p>
      </div>
    </div>
  </div>
 <div class="container">
    <div class="row mt-3">
      <div class="col">
        <h3>Airline Alliances</h3>
        <p class="fs-5">
          The three main airline alliances—Star Alliance, Oneworld, and SkyTeam—connect major airlines worldwide,
            offering passengers seamless travel benefits. Star Alliance, the largest, includes airlines like United, Lufthansa, and Singapore Airlines,
            covering over 1,300 destinations. Oneworld, featuring carriers like American Airlines, British Airways, and Qatar Airways,
            provides premium services and extensive global connectivity. SkyTeam, with members such as Delta, Air France-KLM, and Korean Air,
            focuses on streamlined international travel and shared airport lounges.
            These alliances enhance frequent flyer perks, simplify transfers, and expand route options for travelers globally.
        </p>
      </div>
    </div>
  </div>

airlines/templates/snippets/message_alert.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {%  endfor %}
{% endif %}

airlines/templates/snippets/search_bar.html
<div class="row mb-3">
    <div class="col-8">
        <form method="GET" action="
            {% if request.GET.start_str %}{% url 'airlines:filtered-list-view' start_str=request.GET.start_str %}
            {% else %}{% url 'airlines:list-view' %}
            {% endif %}">
            <input type="text" name="start_str" placeholder="Search airlines..." value="{{ request.GET.start_str }}">
            <button type="submit">Search</button>
        </form>
    </div>
</div>

airlines/templates/snippets/search_bar_airports.html
<div class="row mb-3">
    <div class="col-8">
        <form method="GET" action="
            {% if request.GET.start_str %}{% url 'airlines:filtered-airport-list-view' start_str=request.GET.start_str %}
            {% else %}{% url 'airlines:airport-list-view' %}
            {% endif %}">
            <input type="text" name="start_str" placeholder="Search airports..." value="{{ request.GET.start_str }}">
            <button type="submit">Search</button>
        </form>
    </div>
</div>

airlines/templates/snippets/three_buttons_airlines.html
<div class="d-flex justify-content-end">
        <a href="{% url 'home' %}" class="btn btn-dark me-2">Home Page</a>
        <a href="{% url 'airlines:list-view' %}" class="btn btn-primary me-2">Airline List</a>
        <a href="{% url 'airlines:create-view' %}" class="btn btn-success">Create New</a>
</div>
<hr>

airlines/templates/snippets/three_buttons_airports.html
<div class="d-flex justify-content-end">
        <a href="{% url 'home' %}" class="btn btn-dark me-2">Home Page</a>
        <a href="{% url 'airlines:airport-list-view' %}" class="btn btn-primary me-2">Airports List</a>
        <a href="{% url 'airlines:airport-create-view' %}" class="btn btn-success">Create New</a>
</div>
<hr>