airlines/urls.py
from django.contrib import admin
from django.urls import path, include

# My imports
from airlines.views import  AirlinesListingView, AirlinesDetailView, AirlinesCreateView, AirlineDeleteView, AirlinesUpdateView
#aiport imports
from airlines.views import AirportListView, AirportDetailView, AirportsCreateView, AirportDeleteView, AirportsUpdateView

app_name = "airlines"

urlpatterns = [
    #AIRLINES
    path("list/", AirlinesListingView.as_view(), name="list-view"),
    path("list/<str:start_str>/", AirlinesListingView.as_view(), name="filtered-list-view"),
    path("detail/<int:pk>/", AirlinesDetailView.as_view(), name="detail-view"),
    path("create/", AirlinesCreateView.as_view(), name="create-view"),
    path("delete/<int:pk>/", AirlineDeleteView.as_view(), name="delete-view"),
    path("update/<int:pk>/", AirlinesUpdateView.as_view(), name="update-view"),
    # AIRPORTS
    path("airport-list/", AirportListView.as_view(), name="airport-list-view"),
    path("airport-list/<str:start_str>", AirportListView.as_view(), name="filtered-airport-list-view"),
    path("airport-detail/<int:pk>/", AirportDetailView.as_view(), name="airport-detail-view"),
    path("airport-create/", AirportsCreateView.as_view(), name="airport-create-view"),
    path("airport-delete/<int:pk>/", AirportDeleteView.as_view(), name="airport-delete-view"),
    path("airport-update/<int:pk>/", AirportsUpdateView.as_view(), name="airport-update-view"),
]

project1/urls.py
from airlines.views import  airline_home_page
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
#from project1.views import AccountLoginView, AccountLogoutConfirmationView, AccountLogoutYesNoView, AccountLogoutView

urlpatterns = [
    path("", airline_home_page, name="home"),
    path("admin/", admin.site.urls),
    path("airlines/", include("airlines.urls")),
    # LOGIN LOGOUT
    #path('login-confirmation/', AccountLoginConfirmationView.as_view(), name='login-confirmation'),
    #path('logout-confirmation/', AccountLogoutConfirmationView.as_view(), name='logout-confirmation'),
    #path('logout-yes-no-confirmation/', AccountLogoutYesNoView.as_view(), name='logout-yes-no-confirmation'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout')
]

airlines/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse_lazy

class Alliance(models.Model):
    """Shows to which alliance does each airline belong to"""
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    def alliances_list_as_string(self):
        """Returns a string representation of alliance instances"""
        alliances = self.objects.all()
        return ", ".join(alliance.name for alliance in alliances)

# Basic airline model
class Airline(models.Model):
    airline_name = models.CharField(max_length=100, blank=True)
    airline_code = models.IntegerField( blank=True)
    founded = models.DateField(null=True, blank=True)
    headquarters_city_code = models.CharField(max_length=3, blank=True)

    # Many-to-many relationship with Alliance
    alliance = models.ManyToManyField(Alliance,related_name='airline_alliance', blank=True)

    def get_absolute_url(self):
        """Returns the url to access a detail page of this model"""
        return reverse_lazy('airlines:detail-view', kwargs={'pk': self.pk})

    def __str__(self):
        return self.airline_name


# Basic airport model
class Airport(models.Model):
    airport_name = models.CharField(max_length=100)
    country_code = models.CharField(max_length=2)
    city_code = models.CharField(max_length=3)
    airport_code = models.CharField(max_length=4, unique=True)

    def get_absolute_url(self):
        """Returns the url to access a detail page of this model"""
        return reverse_lazy('airlines:airport-detail-view', kwargs={'pk': self.pk})

    def __str__(self):
        return self.airport_name

airlines/forms.py
from django import forms
from .models import Airline, Airport
from django.core.exceptions import ValidationError

class AirlineModelForm(forms.ModelForm):
    class Meta:
        model = Airline
        fields = "__all__"
        labels = {
            "airline_name": "Airline name",
            "airline_code": "Airline code",
            "founded": "Founded",
            "headquarters_city_code": "Headquarters city code",
        }
        widgets = {
            'alliance': forms.SelectMultiple(attrs={'class': 'form-control'})
        }
        help_texts = {
            "airline_name": "Enter full airline name",
            "airline_code": "Enter three digit airline code",
            "founded": "Enter date when the airline was founded",
            "headquarters_city_code": "Enter three letter city code",
        }

    def clean_airline_name(self):
        """Checking for duplicate data"""
        airline_name = self.cleaned_data.get('airline_name')

        dupe_airline = Airline.objects.filter(airline_name=airline_name).exclude(pk=self.instance.pk).exists()
        if dupe_airline:
            raise ValidationError("Airline name already exists")

        return airline_name

class AirportModelForm(forms.ModelForm):
    class Meta:
        model = Airport
        fields = "__all__"
        labels = {
            "airport_name": "Airport name",
            "country_code": "Country code",
            "city_code": "City code",
            "airport_code": "Airport code",
        }
        help_texts = {
            "airport_name": "Enter full airport name",
            "country_code": "Enter two letter country code",
            "city_code": "Enter three letter city code",
            "airport_code": "Enter three letter airport code",

        }

    def clean_airport_name(self):
        """Checking for duplicate data"""

        airport_name = self.cleaned_data.get("airport_name")

        dupe_airline = Airport.objects.filter(airport_name=airport_name).exclude(pk=self.instance.pk).exists()
        if dupe_airline:
            raise ValidationError("Airport name already exists")

        return airport_name


class JustButtonForm(forms.Form):
    """
    Empty form for just button needs
    """

airlines/views.py
from airlines.models import Airline, Airport
from django.shortcuts import render
from django.db.models import Q

import airlines
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from airlines.forms import AirlineModelForm, AirportModelForm, JustButtonForm
from pyexpat.errors import messages
from django.contrib import messages


#------------------------------------------------------------------------
# AIRLINE VIEWS
#------------------------------------------------------------------------
def airline_home_page(request):
    """Airlines home page"""
    return render(request, 'home_page.html')

class AirlinesListingView(ListView):
    template_name = "airline_listing_template.html"
    model = Airline
    context_object_name = "airlines"

    def get_queryset(self):
        queryset = super().get_queryset()

        start_str = self.request.GET.get('start_str')
        if start_str:
            queryset = queryset.filter(
                Q(airline_name__icontains=start_str) |
                Q(airline_code__icontains=start_str)
            )

        return queryset

class AirlinesDetailView(DetailView):
    template_name = "airline_detail_template.html"
    model = Airline
    context_object_name = "airline"

class AirlinesCreateView(LoginRequiredMixin,CreateView):
    template_name = "airline_create_template.html"
    model = Airline
    form_class = AirlineModelForm
    login_url = reverse_lazy('login')

    def get_success_url(self):
        return self.object.get_absolute_url()

    def dispatch(self, request, *args, **kwargs):
        """Gives error message when not logged in"""
        if not request.user.is_authenticated:
            messages.error(request, message='You have to login to Create a new Airline.')
        return super().dispatch(request, *args, **kwargs)

class AirlineDeleteView(LoginRequiredMixin,DeleteView):
    template_name = "airline_delete_template.html"
    model = Airline
    context_object_name = "airline"
    success_url = reverse_lazy("airlines:list-view")
    form_class = JustButtonForm
    login_url = reverse_lazy('login')

    def dispatch(self, request, *args, **kwargs):
        """Gives error message when not logged in"""
        if not request.user.is_authenticated:
            messages.error(request, message='You have to login to Delete this Airline.')
        return super().dispatch(request, *args, **kwargs)

class AirlinesUpdateView(LoginRequiredMixin,UpdateView):
    template_name = "airline_update_template.html"
    model = Airline
    form_class = AirlineModelForm
    login_url = reverse_lazy('login')

    def dispatch(self, request, *args, **kwargs):
        """Gives error message when not logged in"""
        if not request.user.is_authenticated:
            messages.error(request, message='You have to login to Update Airlines.')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return self.object.get_absolute_url()
#------------------------------------------------------------------------
# AIRPORT VIEWS
#------------------------------------------------------------------------
class AirportListView(ListView):
    template_name = "airport_listing_template.html"
    model = Airport
    context_object_name = "airports"

    def get_queryset(self):
        """Fetches customer imput for filtering airline data"""
        queryset = super().get_queryset()

        start_str = self.request.GET.get('start_str')

        if start_str:
            queryset = queryset.filter(
                Q(airport_name__icontains=start_str) |
                Q(airport_code__icontains=start_str)
            )
        return queryset

class AirportDetailView(DetailView):
    template_name = "airport_detail_template.html"
    model = Airport
    context_object_name = "airport"

class AirportsCreateView(LoginRequiredMixin, CreateView):
    template_name = "airport_create_template.html"
    form_class = AirportModelForm
    login_url = reverse_lazy('login')

    def dispatch(self, request, *args, **kwargs):
        """Gives error message when not logged in"""
        if not request.user.is_authenticated:
            messages.error(request, message='You have to login to Create a new Airport.')
        return super().dispatch(request, *args, **kwargs)


    def get_success_url(self):
        return self.object.get_absolute_url()

class AirportDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "airport_delete_view.html"
    model = Airport
    context_object_name = "airport"
    success_url = reverse_lazy("airlines:airport-list-view")
    login_url = reverse_lazy('login')

    def dispatch(self, request, *args, **kwargs):
        """Gives error message when not logged in"""
        if not request.user.is_authenticated:
            messages.error(request, message='You have to login to Delete Airport.')
        return super().dispatch(request, *args, **kwargs)

class AirportsUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "airport_update_view.html"
    model = Airport
    form_class = AirportModelForm
    login_url = reverse_lazy('login')

    def dispatch(self, request, *args, **kwargs):
        """Gives error message when not logged in"""
        if not request.user.is_authenticated:
            messages.error(request, message='You have to login to Update Airport.')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return self.object.get_absolute_url()

airlines/templates/airline_create_template.html
{% extends 'base_with_bootstrap.html' %}
{% load django_bootstrap5 %}

{% block bootstrap5_title %}Create{% endblock %}

{% block title %}
    Add new airline to the list
    <div class="d-flex justify-content-end">
        <a href="{% url 'home' %}" class="btn btn-dark me-2">Home Page</a>
        <a href="{% url 'airlines:list-view' %}" class="btn btn-primary me-2">Airline List</a>

    </div>
<hr>
{% endblock %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
            {% bootstrap_form form %}
        <br><br>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
{% endblock %}

airlines/templates/airline_delete_template.html
{% extends 'base_with_bootstrap.html' %}
{% load django_bootstrap5 %}

{% block bootstrap5_title %}Delete ({{ airline.pk }}) {% endblock %}

{% block title %}
    You are deleting an airline record
    <!-- Menu buttons -->
    {% include 'snippets/three_buttons_airlines.html' %}
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <!-- Alert Message -->
            <div class="alert alert-warning text-center" role="alert">
                <h5 class="fw-bold">Are you sure you want to delete this airline record?</h5>
                <b><p class="mb-0"><strong>{{ airline.airline_name }} {{ airline.airline_code }}</strong></p></b>
            </div>

            <!-- Form -->
            <div class="card shadow-lg border-danger">
                <div class="card-body text-center">
                    <p class="text-muted">You cannot reverse this action.</p>
                    <form method="post" action="{% url 'airlines:delete-view' airline.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-lg px-4">Delete</button>
                        <a href="{% url 'airlines:list-view' %}" class="btn btn-secondary btn-lg px-4">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

airlines/templates/airline_detail_template.html
{% extends 'base_with_bootstrap.html' %}
{% load django_bootstrap5 %}

{% block bootstrap5_title %}Detail{% endblock %}

{% block title %}
    Airline detail page
    <!-- Menu buttons -->
    {% include 'snippets/three_buttons_airlines.html' %}
    <h3>{{ airline.airline_name }} ({{ airline.airline_code }})</h3>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col">
            <b>Name: </b>
        </div>
        <div class="col">
            <b>Code: </b>
        </div>
        <div class="col">
            <b>Founded: </b>
        </div>
        <div class="col">
            <b>Headquarters city code: </b>
        </div>
        <div class="col">
            <b>Alliance: </b>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ airline.airline_name }}
        </div>
        <div class="col">
            {{ airline.airline_code }}
        </div>
        <div class="col">
            {{ airline.founded }}
        </div>
        <div class="col">
            {{ airline.headquarters_city_code }}
        </div>
        <div class="col">
            {% for alliance in airline.alliance.all %}
	            {{ alliance.name }}{% if not forloop.last %}, {% endif %}
            {% empty %}
	            <span>No alliance</span>
            {% endfor %}
         </div>
    </div>
    <hr>
    <!-- Update Delete buttons -->
    <div class="row">
        <div class="d-flex">
            <a href="{% url 'airlines:update-view' airline.pk %}" class="btn btn-warning me-2">Update</a>
            <a href="{% url 'airlines:delete-view' airline.pk %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
    <br><br>
    <br><br>
    <br><br>
    <br><br>
    <br><br>

{% endblock %}

airlines/templates/airline_listing_template.html
{% extends 'base_with_bootstrap.html' %}
{% load django_bootstrap5 %}

{% block bootstrap5_title %}List Airlines{% endblock %}

{% block title %}
    List of major airlines
    <!-- Menu buttons -->
    <div class="d-flex justify-content-end">
        <a href="{% url 'home' %}" class="btn btn-dark me-2">Home Page</a>
        <a href="{% url 'airlines:create-view' %}" class="btn btn-success">Create New</a>
    </div>

{% endblock %}

{% block content %}
    <!-- Search bar -->
    {%  include 'snippets/search_bar.html' %}

    <div class="row">
        <div class="col-2">
            <b>list number</b>
        </div>
        <div class="col-2">
            <b>Name</b>
        </div>
        <div class="col-2">
            <b>Code</b>
        </div>
        <div class="col-2">
            <b>Founded</b>
        </div>
        <div class="col-2">
            <b>Headquarters</b>
        </div>
    </div>
    <hr>
    {% for airline in airlines %}
        <div class="row my-2">
            <div class="col-2">
                ({{ airline.pk }})
            </div>
            <div class="col-2">
                <a href="{% url 'airlines:detail-view' airline.pk %}" class="text-secondary text-decoration-underline">{{ airline.airline_name }}</a>
            </div>
            <div class="col-2">
                {{ airline.airline_code }}
            </div>
            <div class="col-2">
                {{ airline.founded }}
            </div>
            <div class="col-2">
                {{ airline.headquarters_city_code }}
            </div>
            <!-- Dropdown with options -->
            <div class=col>
                <div class="dropdown">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        options
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'airlines:delete-view' airline.pk %}">Delete</a></li>
                        <li><a class="dropdown-item" href="{% url 'airlines:update-view' airline.pk %}">Update</a></li>
                    </ul>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

airlines/templates/airline_update_template.html
{% extends 'base_with_bootstrap.html' %}
{% load django_bootstrap5 %}

{% block bootstrap5_title %}Update{% endblock %}

{% block title %}
    You are updating details for
    <h3>
        {{ airline.airline_name }} {{ airline.airline_code}}
    </h3>
    <!-- Menu buttons -->
    {% include 'snippets/three_buttons_airlines.html' %}
{% endblock %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
            {%  bootstrap_form form %}
        <br><br>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
{% endblock %}

airlines/templates/airport_create_template.html
{% extends 'base_with_bootstrap.html' %}
{% load django_bootstrap5 %}

{% block bootstrap5_title %}Create Airport{% endblock %}

{% block title %}
    Add new airport to the list
    <!-- Menu buttons -->
    <div class="d-flex justify-content-end">
        <a href="{% url 'home' %}" class="btn btn-dark me-2">Home Page</a>
        <a href="{% url 'airlines:airport-list-view' %}" class="btn btn-primary me-2">Airports List</a>
    </div>
<hr>
{% endblock %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
            {% bootstrap_form form %}
        <br><br>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
{% endblock %}

airlines/templates/airport_delete_view.html
{% extends 'base_with_bootstrap.html' %}
{% load django_bootstrap5 %}

{% block bootstrap5_title %}Delete ({{ airport.pk }}) {% endblock %}

{% block title %}
    You are deleting an airport record
    <!-- Menu buttons -->
    {% include 'snippets/three_buttons_airports.html' %}
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <!-- Alert Message -->
            <div class="alert alert-warning text-center" role="alert">
                <h5 class="fw-bold">Are you sure you want to delete this airport record from the list?</h5>
                <p class="mb-0"><strong>{{ airport.airport_name }} {{ airport.airport_code }}</strong></p>
            </div>

            <!-- Form -->
            <div class="card shadow-lg border-danger">
                <div class="card-body text-center">
                    <p class="text-muted">You cannot reverse this action.</p>
                    <form method="post" action="{% url 'airlines:airport-delete-view' airport.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-lg px-4">Delete</button>
                        <a href="{% url 'airlines:airport-list-view' %}" class="btn btn-secondary btn-lg px-4">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

airlines/templates/airport_detail_template.html
{% extends 'base_with_bootstrap.html' %}
{% load django_bootstrap5 %}

{% block bootstrap5_title %}Airport Detail{% endblock %}

{% block title %}
    Airline detail page
    <!-- Menu buttons -->
    {% include 'snippets/three_buttons_airports.html' %}
    <h3>{{ airport.airport_name }} ({{ airport.airport_code }})</h3>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col">
            <b>Name </b>
        </div>
        <div class="col">
            <b>Country code </b>
        </div>
        <div class="col">
            <b>City code </b>
        </div>
        <div class="col">
            <b>Airport code </b>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ airport.airport_name }}
        </div>
        <div class="col">
            {{ airport.country_code }}
        </div>
        <div class="col">
            {{ airport.city_code }}
        </div>
        <div class="col">
            {{ airport.airport_code }}
        </div>
    </div>
    <hr>
    <!-- Update Delete buttons -->
    <div class="row">
        <div class="d-flex">
            <a href="{% url 'airlines:airport-update-view' airport.pk %}" class="btn btn-warning me-2">Update</a>
            <a href="{% url 'airlines:airport-delete-view' airport.pk %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
    <br><br>
    <br><br>
    <br><br>
    <br><br>
    <br><br>
{% endblock %}

airlines/templates/airport_listing_template.html
{% extends 'base_with_bootstrap.html' %}
{% load django_bootstrap5 %}

{% block bootstrap5_title %}List Airports{% endblock %}

{% block title %}
    List of 100 biggest airports<br>
    <!-- Menu buttons -->
    <div class="d-flex justify-content-end">
        <a href="{% url 'home' %}" class="btn btn-dark me-2">Home Page</a>
        <a href="{% url 'airlines:airport-create-view' %}" class="btn btn-success">Create New</a>
    </div>

{% endblock %}

{% block content %}
    <!-- Search bar -->
    {%  include 'snippets/search_bar_airports.html' %}

    <div class="row">
        <div class="col-2">
            <b>list number</b>
        </div>
        <div class="col-2">
            <b>Name</b>
        </div>
        <div class="col-2">
            <b>Country code</b>
        </div>
        <div class="col-2">
            <b>City code</b>
        </div>
        <div class="col-2">
            <b>Airport code</b>
        </div>
    </div>
    <hr>
    {% for airport in airports %}
        <div class="row my-2">
            <div class="col-2">
                ({{ airport.pk }})
            </div>
            <div class="col-2">
                <a href="{% url 'airlines:airport-detail-view' airport.pk %}" class="text-secondary text-decoration-underline">{{ airport.airport_name }}</a>
            </div>
            <div class="col-2">
                {{ airport.country_code }}
            </div>
            <div class="col-2">
                {{ airport.city_code }}
            </div>
            <div class="col-2">
                {{ airport.airport_code }}
            </div>
            <!-- Dropdown with options -->
            <div class=col>
                <div class="dropdown">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        options
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'airlines:airport-delete-view' airport.pk %}">Delete</a></li>
                        <li><a class="dropdown-item" href="{% url 'airlines:airport-update-view' airport.pk %}">Update</a></li>
                    </ul>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

airlines/templates/airport_update_view.html
{% extends 'base_with_bootstrap.html' %}
{% load django_bootstrap5 %}

{% block bootstrap5_title %}Update{% endblock %}

{% block title %}
    You are updating details for
    <h3>
        {{ airport.airport_name }} {{ airport.airport_code}}
    </h3>
    <!-- Menu buttons -->
    {% include 'snippets/three_buttons_airlines.html' %}
{% endblock %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
            {%  bootstrap_form form %}
        <br><br>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
{% endblock %}

airlines/templates/base_with_bootstrap.html
{% extends 'bootstrap5.html' %}
{% load django_bootstrap5 %}

<title>{% block bootstrap5_title %}bookmark name{% endblock %}</title>

{% block bootstrap5_content %}
    <div class="container">
        <div class="row mt-3">
            <div class="col">
                <h1 class="mt-3">{% block title %}Title of the page{% endblock %}</h1>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col">
            <!-- There will be buttons here later -->
                {% block context_menu %}{% endblock %}&nbsp;&nbsp;
            </div>
        </div>

        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}Our content{% endblock %}
        <!-- footnote -->
        {% include 'snippets/user_info_footnote.html' %}
    </div>
{% endblock %}

airlines/templates/bootstrap5.html
<!DOCTYPE html>
{% load django_bootstrap5 %}
{% if use_i18n %}
    {% load i18n %}
    {% get_current_language as LANGUAGE_CODE %}
{% endif %}
<html lang="{{ LANGUAGE_CODE|default:'en_us' }}">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Page title -->
    <title>{% block bootstrap5_title %}django-bootstrap-v5 template title{% endblock %}</title>

    <!-- Bootstrap CSS -->
    {% bootstrap_css %}

    <!-- Bootstrap JavaScript if it is in head -->
    {% bootstrap_javascript %}

    {% block bootstrap5_extra_head %}{% endblock %}

</head>

<body>
{% block bootstrap5_before_content %}{% endblock %}
{% block bootstrap5_content %} CONTENT {% endblock %}
{% block bootstrap5_after_content %}{% endblock %}

<!-- Bootstrap JavaScript if it is in body -->
{% bootstrap_javascript %}

{% block bootstrap5_extra_script %}{% endblock %}

</body>

</html>

airlines/templates/extend_base_with_bootstrap.html
{% extends 'base_with_bootstrap.html' %}
{% load django_bootstrap5 %}

{% block bootstrap5_title %}bookmark name{% endblock %}

{% block title %}Title of the page{% endblock %}

{% block content %}

    Our content

{% endblock %}

airlines/templates/home_page.html
{% extends 'base_with_bootstrap.html' %}
{% load django_bootstrap5 %}

<title>{% block bootstrap5_title %}Home{% endblock %}</title>

{% block title %}
    Welcome to the Airlines and Airports Page!
        <!-- Menu buttons -->
    <div class="d-flex justify-content-end">
        <a href="{% url 'airlines:list-view' %}" class="btn btn-dark me-2">Airlines List</a>
        <a href="{% url 'airlines:airport-list-view' %}" class="btn btn-success">Airports List</a>
    </div>
{% endblock %}

{% block content %}
    <!-- Text -->
    {% include 'snippets/airline_info1.html' %}
{% endblock %}